version: "3"
services:
  ploneapi:
    build: .
    #image: local/tool:1.0
    ports:
      - 800:8080
    environment:
      CORS_ALLOW_ORIGIN: "*"
    depends_on:
      - memcached
    volumes:
      - data:/data
      - .:/plone/instance/src/clms.downloadtool/
  memcached:
    image: memcached
    command:
      - "-m"
      - "512"
volumes:
  data:
    driver: local
